language: node_js
node_js:
    - "7"

cache:
    bundler: true
    directories:
    - node_modules # NPM packages

branches:
    only:
    - master

notifications:
    email:
        on_success: never
        on_failure: always

after_success:
    npm run build
    gulp deploy --user $FTP_USER --password $FTP_PASSWORD
