language: node_js
node_js:
    - "7"

cache:
    bundler: true
    directories:
    - node_modules

branches:
    only:
    - master

notifications:
    email:
        on_success: never
        on_failure: always

script: npm run build

jobs:
  include:
    - stage: deploy
      gulp deploy --user $FTP_USER --password $FTP_PASSWORD


