"use strict";
var _this = this;
exports.__esModule = true;
var jsx_dev_runtime_1 = require("react/jsx-dev-runtime");
var _jsxFileName = "C:/Users/arcan/git/xianxia-game/src/index.tsx";
var client_1 = require("react-dom/client");
var App = function () { return ((0, jsx_dev_runtime_1.jsxDEV)("div", { children: [(0, jsx_dev_runtime_1.jsxDEV)("h1", { children: "Hello, ESBUILD!" }, void 0, false, { fileName: _jsxFileName, lineNumber: 5, columnNumber: 5 }, _this), (0, jsx_dev_runtime_1.jsxDEV)(Panel, {}, void 0, false, { fileName: _jsxFileName, lineNumber: 6, columnNumber: 5 }, _this), (0, jsx_dev_runtime_1.jsxDEV)(Panel, {}, void 0, false, { fileName: _jsxFileName, lineNumber: 7, columnNumber: 5 }, _this)] }, void 0, true, { fileName: _jsxFileName, lineNumber: 3, columnNumber: 20 }, _this)); };
var Panel = function () { return (0, jsx_dev_runtime_1.jsxDEV)("h2", { children: "Im a Panel" }, void 0, false, { fileName: _jsxFileName, lineNumber: 11, columnNumber: 20 }, _this); };
var root = (0, client_1.createRoot)(document.getElementById('root'));
root.render((0, jsx_dev_runtime_1.jsxDEV)(App, {}, void 0, false, { fileName: _jsxFileName, lineNumber: 15, columnNumber: 13 }, this));
